---
title: Don't pay to meditate
author: A. Solomon Kurz
date: '2018-10-08'
slug: how-bookdown
categories: []
tags:
  - app
  - Insight Timer
  - meditation
  - mindfulness
  - smartphone
header:
  caption: ''
  image: ''
---

The other day, my Twitter feed informed me Penn Jilette just clocked in 1000 consecutive days of meditation using the Headspace app. Now he’s considering checking out Sam Harris’s new Waking Up meditation app. Sam left a congratulatory comment on Penn’s tweet.

{{< tweet 1048730683940646914 >}}

The whole thing was lovely. And it reminded me to pass on some advice: Stop using fee-based meditation apps!

Headspace is popular and highly-rated. It’s free to download and has some nice features, like reminders to meditate. However, if you want full access to its library of guided meditation audio recordings, you’ll need to pay a fee at a monthly, yearly, or lifetime rate. 

The new Waking Up with Sam Harris app is also 

## Consider [Insight Timer](https://insighttimer.com)

[Insight Timer](https://insighttimer.com) comes with a free and pay versions. Just download the free version. It’s excellent and all you need for your meditation needs. Here’s why.

### The library is extensive.

At the time of this writing, my free subscription to Insight Timer gives me access to some 12,000 guided meditation audios. Most of them are in English. But many are offered in other languages, such as Hebrew, Malay, and Spanish.

#### Duration.

The durations vary. The bulk of the guided meditations seem to be in the 5-to-20-minute range. But some last more than an hour.

#### People and their voices.

Their deep library boasts an impressive cast of meditation leaders. I was happy to see some familiar high-profile meditation teachers, such as Tara Brach and Joseph Goldstein. But I’ve new favorites, like Stephen Pende Wormland and Dawn Mauricio. To be sure, the quality of the audio recordings varies. But more importantly, they also vary in terms of vocal tone and pacing. There should be a vocal style to suit just about everyone.

#### Emphasis.

I’m an academic and generally prefer meditations that are secular and connected to the clinical literature. The Insight Timer library contains offerings based on mindfulness-based stress reduction (MBSR) and its derivatives (e.g., mindfulness-based cognitive therapy, mindfulness-based relapse prevention).

But you can also find meditations grounded within a number of faith traditions.

#### Music.

I’ve focused mainly on vocally-driven meditations. However, Insight Timer also contains music/sound-based recordings. I’m partial to recordings featuring Tibetan singing bowls. 

### It’s a timer, too.

Sometimes you just want a silent meditation. For those occasions, Insight Timer offers a nice timer feature. You can set it like a stop watch to whatever duration you prefer, and choose among an array of sounds to mark the beginning and end of the sit.

### It tracks.

If you go to the Profile section of the app, you’ll discover it keeps track of your use and displays various summaries in attractive bar plots [Yes, I agree with McElreath: "The only problem with barplots is that they have bars" (p. 203, [*Statistical Rethinking*](https://bookdown.org/connect/#/apps/1850/access)). You can’t have everything.]. Which leads me to my next point.

## Insight Timer is great for researchers

Insight Timer allows you to download your data as a CSV file, which you can keep for yourself or email to others. Over the years, I’ve used the app to run group meditations within my research protocols. Since I selected the audios from the app, it allowed me to standardize the instructions across meditation sessions. Although I or one of my research assistants used the app on our phones to play the audios, our participants would use the timer functions on the apps on their phones to record their sessions. This gave us duplicate attendance records: one on a sign-in sheet and another on their phones. In longitudinal studies, participants could use the app on their own time and each of those sessions were recorded in the app. At the study, we were then able to download their use records as CSV files ready for pre-analysis data wrangling.

## Parting thoughts

Insight Timer has other functions, such as social networking and dharma talks. I just don’t care about those things, so you can learn about them on your own. But if you’re interested in learning about meditation or even if you’re a veteran meditator looking for a convenient app to augment your practice with, do consider Insight Timer. There’s no reason to spend your money on the alternatives when this powerful of a resource is available to you for free.


